submit = Aceptar
struts.devMode=false
appName = puntodeventa
servPath = /app/puntodeventa/
username = root
password = Puebla123
url=jdbc:mysql://localhost:3306/puntoventa?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
driver=com.mysql.cj.jdbc.Driver
#PathImagesLocal = C:\\images\\puntoventa\\
PathImagesLocal = /home/images/puntoventa/
#PathReportesLocal = C:\\Users\\Dell\\workspace\\puntodeventa\\WebContent\\docs\\reportes\\
PathReportesLocal = C:\\puntoventa\\tickets\\2026\\02\\
